let covidEssentials = () => { return {
    bannerImg : "https://www.netmeds.com/images/cms/aw_rbslider/slides/1649267860_Category_Banners_web_1000px_x_200px.jpg",
    mastCata : 
    [
        {
            catagoryImg : "https://www.netmeds.com/images/category/3066/thumb/personal_home_essentials_1.jpg",
            name : "Personal & home" ,
            disc : 75 ,
            catagories :
            { 
                subBanner : false, 
                data : 
                [
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/15114/dettol_antiseptic_liquid_60_ml_0_1.jpg",
                        name : "Dettol Antiseptic Liquid 60 ml",
                        mkt : "Reckitt Benckiser India Ltd",
                        price : 33,
                        strike : false ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/835057/dettol_antiseptic_liquid_550_ml_0.jpg",
                        name : "Dettol Antiseptic Liquid 550 ml",
                        mkt : "Reckitt Benckiser India Ltd",
                        price : 194,
                        strike : false ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/102099/dettol_antiseptic_liquid_1_ltr_0_1.jpg",
                        name : "Dettol Antiseptic Liquid 1 ltr",
                        mkt : "Reckitt Benckiser India Ltd",
                        price : 331,
                        strike : false ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/102099/dettol_antiseptic_liquid_1_ltr_0_1.jpg",
                        name : "Dettol Antiseptic Liquid Disinfectant 250 ml",
                        mkt : "Reckitt Benckiser India Ltd",
                        price : 116,
                        strike : false ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/15116/dettol_disinfectant_lime_fresh_500_ml_0_1.jpg",
                        name : "Dettol Disinfectant -Lime Fresh 500 ml",
                        mkt : "Reckitt Benckiser India Ltd",
                        price : 192,
                        strike : 193 ,
                    } ,
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/412802/dettol_disinfectant_liquid_menthol_cool_500_ml_0.jpg",
                        name : "Dettol Disinfectant Liquid -Menthol cool 500 ml",
                        mkt : "Reckitt Benckiser India Ltd",
                        price : 192,
                        strike : 193 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/15115/dettol_disinfectant_lime_fresh_200_ml_0_1.jpg",
                        name : "Dettol Disinfectant -lime Fresh 200 ml",
                        mkt : "Reckitt Benckiser India Ltd",
                        price : 97,
                        strike : 98 ,
                    },
                    {    
                        image : "https://www.netmeds.com/images/product-v1/150x150/406018/savlon_antiseptic_liquid_100_ml_0_1.jpg",      
                        name : "Savlon Antiseptic Liguid 100 ml",
                        mkt : "Reckitt Benckiser India Ltd",
                        price : 48,
                        strike : false ,
                    },
                    {    image : "https://www.netmeds.com/images/product-v1/150x150/412801/dettol_disinfectant_liquid_menthol_cool_200_ml_0.jpg",
                        name : "Dettol Disinfectant Liguid -Menthol Cool 200ml",
                        mkt : "Reckitt Benckiser India Ltd",
                        price : 97,
                        strike : 98 ,
                    },
                    {    image : "https://www.netmeds.com/images/product-v1/150x150/408712/romsons_respirometer_0.jpg",
                        name : "Romsons Respirometer",
                        mkt : "Romsons Scientific & surgical P ...",
                        price : 160,
                        strike : 773,
                    },
                    {    image : "https://www.netmeds.com/images/product-v1/150x150/902228/sahyog_wellness_hot_water_bottle_bag_blue_0_1.jpg",
                        name : "Sahyog Wellness Hot Water Bottle?Bag -Blue",
                        mkt : "Sayyog Wellness",
                        price : 249,
                        strike : 300 ,
                    },
                    {    image : "https://www.netmeds.com/images/product-v1/150x150/859708/omron_compressor_nebulizer_ne_c101_0.jpg",
                        name : "Omron Compressor Nebulizer (NE-C101)",
                        mkt : "Omron Healthcore Co Ltd",
                        price : 1904,
                        strike : 2380 ,
                    } ,
                    {    image : "https://www.netmeds.com/images/product-v1/150x150/815757/chicco_disinfectant_multipurpose_500_ml_0_1.jpg",
                        name : "Chicco Disinfectant Multipurpose 500 ml",
                        mkt : "Artsala India Pvt Ltd",
                        price : 299,
                        strike : false ,
                    },
                    {    image : "https://www.netmeds.com/images/product-v1/150x150/912261/ciphands_daily_surface_disinfectant_spray_75_ml_0_3.jpg",
                    name : "disinfevtant Sparay 75 ml",
                    mkt : "Cipla Ltd (otc)",
                    price : 94,
                    strike : 99 ,
                },
                {    image : "https://www.netmeds.com/images/product-v1/150x150/915643/zebronics_fingertip_pulse_oximeter_zeb_fpo500_0_0.jpg",
                        name : "ZEbronics Fingertip Pulse Oximeter (ZeB-FPO500)",
                        mkt : "Zebronics India Private Limited",
                        price : 659,
                        strike : 2999 ,
                    },
                    {    image : "https://www.netmeds.com/images/product-v1/150x150/947290/wonder_vaporizer_steam_inhaler_0_0.jpg",
                        name : "Wonder VAporizer Steam Inhaler",
                        mkt : "Wonder Plast Products",
                        price : 220,
                        strike : 359 ,
                    },
                    {    image : "https://www.netmeds.com/images/product-v1/150x150/987148/ab_find_post_vaccination_neutralizing_antibody_test_1s_0_0.jpg",
                    name : "AB Find Post Vaccination Neutralizing antibody Test Kit ",
                    mkt : "Diagnostics Private Limited",
                    price : 284,
                    strike : 299 ,
                },
                {    image : "https://www.netmeds.com/images/product-v1/150x150/959012/detelpro_juren_oxygen_concentrator_1_7_lpm_1s_0_0.jpg",
                        name : "DetelPro Juren Oxygen Concentractor (1-7 LPM)",
                        mkt : "SG Corporate MobilityPvt Ltd",
                        price : 39000,
                        strike : 600000 ,
                    } ,
                    {    image : "https://www.netmeds.com/images/product-v1/150x150/938163/hyginium_hand_sanitizer_110_ml_0_2.jpg",
                        name : "Hyginium Had Sanitizer 110 ml",
                        mkt : "Troikaa Phoemaceuticals sLtd ",
                        price : 35,
                        strike : 88 ,
                    } ,
                    {    image : "https://www.netmeds.com/images/product-v1/150x150/939990/puric_instasafe_hygiene_hand_sanitizer_gel_camphor_citrus_100_ml_0_0.jpg",
                        name : "Puric InstaSafe Hygiene Hand Sanitizer Gel -Comphor & Citrus",
                        mkt : "Reliance Retail Limited",
                        price : 50,
                        strike : false ,
                    } 
                    
                      
                ]
            }
        },
        {
            catagoryImg : "https://www.netmeds.com/images/category/3065/thumb/mask_gloves_protective_equipment_1.jpg",
            name : "Mask,Gloves & pr..." ,
            disc : 88,
            catagories :
            { 
                subBanner : false, 
                data : 
                [
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/958409/status_n95_face_mask_white_pack_of_20_0_1.jpg",
                        name : "Status N95 Face MAsk -White 9Pack of 20)",
                        mkt : "Chinar Forge Ltd ",
                        price : 200,
                        strike : 980 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/915736/r_m_pharma_face_shield_0_0.jpg",
                        name : "R.M Phorma Face Shield ",
                        mkt : "R.M. Phorma And Surgicals ",
                        price : 19,
                        strike : 100 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/945279/mahalaxmi_enterprises_3_ply_face_mask_100s_0_0.jpg",
                        name : "Mahalaxmi enterprises 3 ply Face Mask 100's",
                        mkt : "Mahalaxmi Enterprises",
                        price : 192,
                        strike : 1600 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/996634/savi_n95_face_mask_5_layer_10s_0_0.jpg",
                        name : "Savi N95 Face MAs 5 Layer 10's",
                        mkt : "SAVI FORTUNES PVT LTD",
                        price : 283,
                        strike : 810 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/994661/smyle_n95_mask_1s_0_0.jpg",
                        name : "Smyle N95 MAsk 1's",
                        mkt : "Svizera Health Remedies LLd",
                        price : 120,
                        strike : false ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/992326/o2_anti_pollution_n99_face_mask_7_layer_1s_0_0.jpg",
                        name : "o2+anti Pollition N99 Face MAsk 7 Layer 1's",
                        mkt : "HRIM LABS ",
                        price : 509,
                        strike : 599 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/992325/o2_anti_pollution_n99_face_mask_6_layer_1s_0_0.jpg",
                        name : "o2+anti Pollition N99 Face MAsk 6 Layer 1's",
                        mkt : "HRIM LABS",
                        price : 296,
                        strike : 349 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/969035/advind_smog_guard_n95_kids_mask_xs_yellow_1s_0_0.jpg",
                        name : "Advind Smog Guard N95 For 3-5 Years Kids Mask (XS)",
                        mkt : "Advind Helathcare India PVT.Ltd",
                        price : 174,
                        strike : 294 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/969034/advind_smog_guard_n95_kids_mask_xs_blue_1s_0_0.jpg",
                        name : "Advind Smog Guard N95 For 3-5 Years Kids Mask (XS)-blue",
                        mkt : "Advind Helathcare India PVT.Ltd",
                        price : 174,
                        strike : 249 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/969035/advind_smog_guard_n95_kids_mask_xs_yellow_1s_0_0.jpg",
                        name : "Advind Smog Guard N95 For 3-5 Years Kids Mask (XS)-Beige",
                        mkt : "Advind Helathcare India PVT.Ltd",
                        price : 174,
                        strike : 249,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/969035/advind_smog_guard_n95_kids_mask_xs_yellow_1s_0_0.jpg",
                        name : "Advind smog GUard N95 For 6-10 Years Kids Face Mask(s)",
                        mkt : "Advind Helathcare India PVT.Ltd",
                        price : 174,
                        strike : 294,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/969034/advind_smog_guard_n95_kids_mask_xs_blue_1s_0_0.jpg",
                        name : "Advind Smog GuardN95 For 6-10 Years Kids Face Mask (s)-Blue",
                        mkt : "Advind Helathcare India PVT.Ltd",
                        price : 174,
                        strike : 249 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/969029/advind_smog_guard_n95_kids_mask_truck_printed_design_1s_0_0.jpg",
                        name : "Advind Smog Guard N95 For 4-12 Years Kids Face Mask-Truck",
                        mkt : "Advind Healthcare India Pvt.Ltd",
                        price : 139,
                        strike : 199 ,
                    } ,
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/969028/advind_smog_guard_n95_for_4_12_years_kids_face_mask_car_printed_design_1s_0_1.jpg",
                        name : "Advind Smog Guard N95 For 4-12 Years Kids Face Mask-Car",
                        mkt : "Advind Healthcare India Pvt.Ltd",
                        price : 139,
                        strike : 199 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/969027/advind_smog_guard_n95_for_4_12_years_kids_face_mask_pink_printed_design_1s_0_1.jpg",
                        name : "Advind Smog Guard N95 For 4-12 Years Kids Face Mask-Pink",
                        mkt : "Advind Healthcare India Pvt.Ltd",
                        price : 139,
                        strike : 199 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/969026/advind_smog_guard_n95_kids_mask_blue_printed_design_1s_0_0.jpg",
                        name : "Advind Smog Guard N95 For 4-12 Years Kids Face Mask-Blue",
                        mkt : "Advind Healthcare India Pvt.Ltd",
                        price : 139,
                        strike : 199 ,
                    }      

                ]
            }
        },
        {
            catagoryImg : "https://www.netmeds.com/images/category/3061/thumb/immunity_booster_1.jpg",
            name :"immunity booster " ,
            disc : 545 ,
            catagories :
            { 
                subBanner : "https://www.netmeds.com/images/cms/aw_rbslider/slides/1649268453_Category_Banners_web_2_1000px_x_200px.jpg", 
                data : 
                [
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/113742/revital_h_capsule_10_s_0.jpg",
                        name : "Revital Capsule 10's",
                        mkt : "Sun Pharmaceutical Industries l..",
                        price : 95,
                        strike : 110 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/407923/revital_h_woman_tablet_30_s_0.jpg",
                        name : "Revital H Women Tablet 30'S",
                        mkt : "Sun Pharmaceutical Industries l..",
                        price : 293,
                        strike : 345 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/113653/revital_h_capsule_60_s_0.jpg",
                        name : "Revital H Capsule 60's",
                        mkt : "Sun Pharmaceutical Industries l..",
                        price : 467,
                        strike : 550 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/328123/revital_h_capsule_30_s_0.jpg",
                        name : "Revital H Capsule 30's",
                        mkt : "Sun Pharmaceutical Industries l..",
                        price : 263,
                        strike : 310,
                         
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/408222/revital_h_woman_tablet_10_s_0.jpg",
                        name : "Revital H Women Tablet 10's",
                        mkt : "Sun Pharmaceutical Industries l..",
                        price : 102,
                        strike : 120 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/38049/garlic_pearls_capsule_100_s_0.jpg",
                        name : "Garlic Pearls Capsule 100's",
                        mkt : "Sun Pharmaceutical Industries l..",
                        price : 127,
                        strike : 150 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/839437/fast_up_charge_natural_vitamin_c_tablets_orange_flavour_20_s_0.jpg",
                        name : "Fast&up Charge Natural Vitamin C & Zinc Tablets-Orange Flavour",
                        mkt : "Aeronutrix sports Products Priv...",
                        price : 300,
                        strike : 390 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/815146/healthvit_fitness_zma_zinc_magnesium_vitamin_b6_capsules_90_s_0.jpg",
                        name : "HealthVit Fitness ZMA(Zinc, Magnesium & Vitamin B6) ",
                        mkt : "West Coast Pharmaceuticals W..",
                        price : 946,
                        strike : 1100 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/885336/fast_up_charge_effervesent_tablet_orange_flavour_pack_of_3_x_20_s_0.jpg",
                        name : "Fast & Up Charge Natural Vitamin C & Zinc Effervesent Tablet",
                        mkt : "AeroNutrix Sports Products Priv..",
                        price : 850,
                        strike : 1170 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/412506/dr_vaidyas_herbofit_capsule_30s_0_1.jpg",
                        name : "Dr.Vaidya's Herbofit Capsule 30's",
                        mkt : "HErbolab India Pvt Ltd",
                        price : 156,
                        strike : 180 ,
                    },
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/815541/healthvit_mulvit_multivitamins_and_minerals_tablet_60_s_0.jpg",
                        name : "Health Vit Mulvit Multivitamins And Minerals Tablet 60's",
                        mkt : "West Coast Pharmaceuticals W...",
                        price : 360,
                        strike : 400 ,
                    } ,
                    {
                        image : "https://www.netmeds.com/images/product-v1/150x150/842857/healthvit_cenvitan_women_multivitamin_multimineral_tablet_60s_0_2.jpg",
                        name : "HealthVit Cenvitan Women (Multivitamin & Multimineral)",
                        mkt : "West Coast Pharmaceuticals W...",
                        price : 473,
                        strike : 550 ,
                    } 
                ]
            }
        },
       
    ]
}
}

export {covidEssentials};